variable "project_id" {
  description = "GCP project that owns the GKE cluster and Artifact Registry repository."
  type        = string
}

variable "region" {
  description = "GCP region for regional resources."
  type        = string
  default     = "us-central1"
}

variable "cluster_name" {
  description = "GKE cluster name."
  type        = string
  default     = "argus-gke"
}

variable "namespace" {
  description = "Kubernetes namespace for Argus workloads."
  type        = string
  default     = "argus"
}

variable "artifact_registry_repository" {
  description = "Artifact Registry Docker repository for Argus images."
  type        = string
  default     = "argus"
}

# ── Core node pool (stateful services, databases, API gateway, web) ──────────

variable "core_machine_type" {
  description = "Machine type for the core-services node pool."
  type        = string
  default     = "n2-standard-8"
}

variable "core_disk_size_gb" {
  description = "Boot disk size in GB for core service nodes."
  type        = number
  default     = 200
}

# ── Worker node pool (autoscaling background workers) ─────────────────────────

variable "worker_machine_type" {
  description = "Machine type for the worker autoscaling node pool."
  type        = string
  default     = "e2-standard-4"
}

variable "min_node_count" {
  description = "Minimum worker nodes (can scale to zero when idle)."
  type        = number
  default     = 0
}

variable "max_node_count" {
  description = "Maximum worker nodes."
  type        = number
  default     = 3
}

# ── Aspirate / workloads ──────────────────────────────────────────────────────

variable "apply_aspirate_manifests" {
  description = "When true, apply YAML generated by Aspirate."
  type        = bool
  default     = false
}

variable "aspirate_manifest_dir" {
  description = "Path to Aspirate generated Kubernetes YAML, relative to deploy/terraform."
  type        = string
  default     = "../../src/Argus.AppHost/aspirate-output"
}

variable "create_worker_hpas" {
  description = "Create Kubernetes HPAs for continuous background workers generated by Aspirate."
  type        = bool
  default     = true
}

variable "worker_min_replicas" {
  description = "Default minimum replicas for continuous workers."
  type        = number
  default     = 1
}

variable "worker_max_replicas" {
  description = "Default maximum replicas for continuous workers."
  type        = number
  default     = 20
}

variable "worker_cpu_utilization" {
  description = "Average CPU utilization percentage that drives continuous worker HPAs."
  type        = number
  default     = 70
}

variable "install_keda" {
  description = "Install KEDA so queue/custom metric scaled workers can be added without changing cluster provisioning."
  type        = bool
   default     = true
}
