<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Argus.BuildingBlocks.EventBus\Argus.BuildingBlocks.EventBus.csproj" />
    <ProjectReference Include="..\..\Contracts\Argus.Contracts\Argus.Contracts.csproj" />
    <ProjectReference Include="..\..\Argus.ServiceDefaults\Argus.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
