/* eslint-disable */
// Mock data for the Development section: agents + agent tasks.

const AGENT_CLIS = [
  { id: "claude",   label: "claude",   color: "amber",   command: "claude --print" },
  { id: "codex",    label: "codex",    color: "green",   command: "codex exec" },
  { id: "opencode", label: "opencode", color: "cyan",    command: "opencode run" },
];

const AGENT_MODELS = {
  claude:   ["claude-sonnet-4-5", "claude-opus-4-5", "claude-haiku-4-5"],
  codex:    ["gpt-5-codex", "gpt-5", "o3-mini"],
  opencode: ["qwen3-coder-480b", "deepseek-v3.1", "kimi-k2", "glm-4.6"],
};

const AGENT_ROLES = [
  { id: "development", label: "Dev",      color: "cyan",    glyph: "λ" },
  { id: "devops",      label: "DevOps",   color: "amber",   glyph: "⌗" },
  { id: "reviewer",    label: "Reviewer", color: "magenta", glyph: "◆" },
  { id: "qa",          label: "QA",       color: "green",   glyph: "✓" },
];

const SCHED_PRESETS = [
  { id: "every-30m",  label: "every 30m",  cron: "*/30 * * * *" },
  { id: "every-2h",   label: "every 2h",   cron: "0 */2 * * *" },
  { id: "every-6h",   label: "every 6h",   cron: "0 */6 * * *" },
  { id: "daily-9am",  label: "daily 09:00 UTC", cron: "0 9 * * *" },
  { id: "on-event",   label: "on git-push", cron: "@event:git.push" },
  { id: "continuous", label: "continuous", cron: "@continuous" },
];

const AGENT_RUN_HISTORY = (n) => Array.from({ length: n }, (_, i) => ({
  startedAt: Date.now() - (i + 1) * (rint(2, 30) * 60_000),
  duration: rint(8, 240) * 1000,
  status: i === 0 ? (Math.random() < 0.7 ? "completed" : "stalled") : (Math.random() < 0.84 ? "completed" : Math.random() < 0.5 ? "failed" : "stalled"),
  tokensIn: rint(2000, 18000),
  tokensOut: rint(500, 4500),
  taskId: (52 - i).toString().padStart(3, "0"),
  cost: (Math.random() * 0.34 + 0.01),
}));

const AGENTS = [
  {
    id: "agent-1",
    name: "Agent 1",
    role: "development",
    cli: "claude",
    model: "claude-sonnet-4-5",
    enabled: true,
    workStatus: "working",
    currentTask: "052",
    currentDescription: "Enhancement #18: Program/scope export and import — GET /programs/{programId}/export returns JSON, POST /programs/import reconstructs full config.",
    pid: 14283,
    cwd: "/srv/argus",
    startedAt: Date.now() - 47 * 60_000,
    lastHeartbeat: Date.now() - 3 * 1000,
    lastError: null,
    promptPreview: "You are a senior C# engineer working on the ArgusEngine codebase. Implement the assigned enhancement with idiomatic .NET 8…",
    attempts: 2,
    tokensToday: 412_800,
    costToday: 2.34,
    runs24h: 18,
    successRate: 91.6,
    recurring: [
      { id: "r1", label: "Pick next priority task", cron: "*/2 * * * *",  enabled: true,  lastRun: Date.now() - 90_000 },
      { id: "r2", label: "Run dotnet build & report errors", cron: "0 */1 * * *", enabled: true, lastRun: Date.now() - 24 * 60_000 },
    ],
    history: AGENT_RUN_HISTORY(14),
  },
  {
    id: "agent-2",
    name: "Agent 2",
    role: "development",
    cli: "codex",
    model: "gpt-5-codex",
    enabled: true,
    workStatus: "idle",
    currentTask: null,
    currentDescription: null,
    pid: 14299,
    cwd: "/srv/argus",
    startedAt: Date.now() - 4 * 3600_000,
    lastHeartbeat: Date.now() - 9 * 1000,
    lastError: null,
    promptPreview: "Implementation specialist for backend services. Prefer minimal diffs, write tests, follow existing patterns…",
    attempts: 0,
    tokensToday: 287_400,
    costToday: 1.68,
    runs24h: 12,
    successRate: 88.4,
    recurring: [
      { id: "r1", label: "Pick next priority task", cron: "*/2 * * * *",  enabled: true,  lastRun: Date.now() - 110_000 },
    ],
    history: AGENT_RUN_HISTORY(10),
  },
  {
    id: "agent-3",
    name: "Agent 3",
    role: "development",
    cli: "claude",
    model: "claude-opus-4-5",
    enabled: true,
    workStatus: "working",
    currentTask: "054",
    currentDescription: "Bug #41: HeadlessSpider OOM under heavy SPA load — investigate, reproduce, and patch playwright pool eviction.",
    pid: 14411,
    cwd: "/srv/argus",
    startedAt: Date.now() - 12 * 60_000,
    lastHeartbeat: Date.now() - 1 * 1000,
    lastError: null,
    promptPreview: "Investigation & deep bug fixes. Prefer experiments + thoughtful reasoning over rushing patches…",
    attempts: 1,
    tokensToday: 904_200,
    costToday: 8.74,
    runs24h: 9,
    successRate: 94.2,
    recurring: [
      { id: "r1", label: "Triage failed builds", cron: "*/15 * * * *", enabled: true, lastRun: Date.now() - 4 * 60_000 },
      { id: "r2", label: "Investigate flaky tests",  cron: "0 */6 * * *", enabled: true, lastRun: Date.now() - 4 * 3600_000 },
    ],
    history: AGENT_RUN_HISTORY(11),
  },
  {
    id: "agent-4",
    name: "Agent 4",
    role: "development",
    cli: "opencode",
    model: "qwen3-coder-480b",
    enabled: true,
    workStatus: "idle",
    currentTask: null,
    currentDescription: null,
    pid: 14478,
    cwd: "/srv/argus",
    startedAt: Date.now() - 6 * 3600_000,
    lastHeartbeat: Date.now() - 6 * 1000,
    lastError: null,
    promptPreview: "Generalist contributor. Bias toward small, well-tested commits. Reach for existing helpers before inventing new ones…",
    attempts: 0,
    tokensToday: 198_400,
    costToday: 0.42,
    runs24h: 14,
    successRate: 82.1,
    recurring: [
      { id: "r1", label: "Pick next priority task", cron: "*/2 * * * *",  enabled: true,  lastRun: Date.now() - 60_000 },
    ],
    history: AGENT_RUN_HISTORY(12),
  },
  {
    id: "agent-5",
    name: "Agent 5",
    role: "development",
    cli: "claude",
    model: "claude-sonnet-4-5",
    enabled: true,
    workStatus: "stalled",
    currentTask: "048",
    currentDescription: "Design #20: RealtimeService fully in-memory — needs durability. Add ledger persistence and replay-on-restart.",
    pid: null,
    cwd: "/srv/argus",
    startedAt: Date.now() - 84 * 60_000,
    lastHeartbeat: Date.now() - 184 * 1000,
    lastError: "agent exited with code 0 before task completion (task status: in_progress)",
    promptPreview: "Implementation specialist…",
    attempts: 4,
    tokensToday: 612_000,
    costToday: 4.18,
    runs24h: 7,
    successRate: 74.0,
    recurring: [
      { id: "r1", label: "Pick next priority task", cron: "*/2 * * * *", enabled: true, lastRun: Date.now() - 320_000 },
    ],
    history: AGENT_RUN_HISTORY(9),
  },
  {
    id: "devops-1",
    name: "DevOps 1",
    role: "devops",
    cli: "codex",
    model: "gpt-5",
    enabled: true,
    workStatus: "working",
    currentTask: "ops-12",
    currentDescription: "Watch docker compose health, restart failed workers, ensure NATS + Postgres up.",
    pid: 14502,
    cwd: "/srv/argus/deploy",
    startedAt: Date.now() - 2 * 3600_000,
    lastHeartbeat: Date.now() - 2 * 1000,
    lastError: null,
    promptPreview: "DevOps custodian. Keep the deployment healthy. You can run docker, compose, kubectl, ssh, terraform…",
    attempts: 0,
    tokensToday: 84_200,
    costToday: 0.92,
    runs24h: 142,
    successRate: 99.1,
    recurring: [
      { id: "r1", label: "Health probe all services", cron: "*/5 * * * *", enabled: true,  lastRun: Date.now() - 90_000 },
      { id: "r2", label: "Rotate logs",                cron: "0 4 * * *",  enabled: true,  lastRun: Date.now() - 11 * 3600_000 },
      { id: "r3", label: "Backup postgres ledger",     cron: "0 */6 * * *",enabled: true,  lastRun: Date.now() - 2 * 3600_000 },
      { id: "r4", label: "Update worker images",       cron: "0 6 * * *",  enabled: false, lastRun: Date.now() - 26 * 3600_000 },
    ],
    history: AGENT_RUN_HISTORY(20),
  },
  {
    id: "reviewer-1",
    name: "Reviewer 1",
    role: "reviewer",
    cli: "claude",
    model: "claude-sonnet-4-5",
    enabled: true,
    workStatus: "working",
    currentTask: "rev-08",
    currentDescription: "Review uncommitted diff in src/Workers/Argus.Workers.HeadlessSpider/ for correctness and style.",
    pid: 14530,
    cwd: "/srv/argus",
    startedAt: Date.now() - 6 * 60_000,
    lastHeartbeat: Date.now() - 4 * 1000,
    lastError: null,
    promptPreview: "Senior reviewer. Critique code for correctness, performance, idiomaticity, and security. Be terse.",
    attempts: 0,
    tokensToday: 222_400,
    costToday: 1.91,
    runs24h: 38,
    successRate: 97.8,
    recurring: [
      { id: "r1", label: "Review uncommitted diff",    cron: "*/10 * * * *", enabled: true, lastRun: Date.now() - 4 * 60_000 },
      { id: "r2", label: "Review last commit on main", cron: "@event:git.push", enabled: true, lastRun: Date.now() - 38 * 60_000 },
    ],
    history: AGENT_RUN_HISTORY(16),
  },
  {
    id: "reviewer-2",
    name: "Reviewer 2",
    role: "reviewer",
    cli: "opencode",
    model: "deepseek-v3.1",
    enabled: false,
    workStatus: "idle",
    currentTask: null,
    currentDescription: null,
    pid: null,
    cwd: "/srv/argus",
    startedAt: null,
    lastHeartbeat: Date.now() - 6 * 3600_000,
    lastError: null,
    promptPreview: "Secondary reviewer. Focus on security review of newly-exposed endpoints.",
    attempts: 0,
    tokensToday: 0,
    costToday: 0,
    runs24h: 0,
    successRate: 0,
    recurring: [
      { id: "r1", label: "Security review on new endpoints", cron: "*/30 * * * *", enabled: false, lastRun: null },
    ],
    history: [],
  },
];

// Agent tasks queue (separate from worker tasks — these are dev tasks for AI agents)
const AGENT_TASK_STATUSES = ["pending", "claimed", "in_progress", "blocked", "completed", "failed", "abandoned"];

const RAW_DEV_TASKS = [
  ["052", "Enhancement #18: Program/scope export and import",        "high",   "in_progress", "agent-1",    "feature"],
  ["053", "Bug #43: Asset deduplication race in NormalizationWorker", "high",   "claimed",     "agent-3",    "bug"],
  ["054", "Bug #41: HeadlessSpider OOM under heavy SPA load",         "critical","in_progress","agent-3",    "bug"],
  ["055", "Enhancement #19: Per-target rate-limit policies",          "medium", "pending",     null,         "feature"],
  ["056", "Enhancement #20: Subscription filter DSL",                 "medium", "pending",     null,         "feature"],
  ["057", "Refactor: extract WorkerLeaseService into shared lib",     "low",    "pending",     null,         "refactor"],
  ["058", "Bug #44: SSE event ordering jitter under burst",           "high",   "pending",     null,         "bug"],
  ["059", "Docs: producer/consumer matrix for worker types",          "low",    "pending",     null,         "docs"],
  ["060", "Migrate JsExtractor to playwright-stealth",                "medium", "pending",     null,         "chore"],
  ["061", "Add metrics: queue depth per worker capability",           "medium", "pending",     null,         "feature"],
  ["062", "Bug #45: Checkpoint resume drops cursor on retry > 3",     "critical","pending",    null,         "bug"],
  ["063", "Add Reviewer agent feedback loop in PR comments",          "low",    "pending",     null,         "feature"],
  ["064", "Snyk scan: 3 high CVEs in Argus.Web deps",                 "high",   "blocked",     "devops-1",   "security"],
  ["065", "Enhancement #21: Asset scoring weights configurable",      "medium", "pending",     null,         "feature"],
  ["066", "Bug #46: Subfinder rate-limited by Shodan above 30 rpm",   "medium", "pending",     null,         "bug"],
  ["051", "Enhancement #17: Bulk-tag editor in UI",                   "medium", "completed",   "agent-1",    "feature"],
  ["050", "Bug #40: HttpProbe follows redirect into OOS host",        "high",   "completed",   "agent-3",    "bug"],
  ["049", "Refactor: switch outbox dispatcher to channels",           "low",    "completed",   "agent-2",    "refactor"],
  ["048", "Design #20: RealtimeService durability",                   "medium", "failed",      "agent-5",    "feature"],
  ["047", "Bug #39: Asset confidence stuck at 50%",                   "high",   "completed",   "agent-4",    "bug"],
  ["046", "Add Prometheus exporters for worker metrics",              "medium", "completed",   "devops-1",   "feature"],
  ["045", "Bug #38: WordlistDiscovery respects 429 backoff",          "high",   "completed",   "agent-1",    "bug"],
  ["rev-08","Review diff: HeadlessSpider playwright pool",            "low",    "in_progress", "reviewer-1", "review"],
  ["rev-07","Review diff: AssetScoring weight changes",               "low",    "completed",   "reviewer-1", "review"],
  ["ops-12","Restart degraded HttpProbe instance w-httpprobe-002",    "high",   "in_progress", "devops-1",   "ops"],
  ["ops-11","Rotate API gateway TLS cert",                            "medium", "pending",     null,         "ops"],
];

const AGENT_TASKS = RAW_DEV_TASKS.map(([id, desc, priority, status, assigned, kind], i) => ({
  id,
  description: desc,
  priority,
  status,
  assignedTo: assigned,
  kind,
  createdAt: Date.now() - (RAW_DEV_TASKS.length - i) * rint(6, 90) * 60_000,
  claimedAt: status !== "pending" ? Date.now() - rint(1, 240) * 60_000 : null,
  completedAt: status === "completed" || status === "failed" ? Date.now() - rint(2, 720) * 60_000 : null,
  attempts: status === "completed" ? rint(1, 3) : status === "failed" ? rint(2, 5) : status === "in_progress" ? rint(1, 2) : 0,
  prompt: `Implement: ${desc}\n\nFollow ArgusEngine conventions. Add tests. Update docs if behavior changes.`,
  blockedReason: status === "blocked" ? "Awaiting security review · dependency upgrade requires breaking-change SLA" : null,
}));

Object.assign(window, {
  AGENTS, AGENT_TASKS, AGENT_CLIS, AGENT_MODELS, AGENT_ROLES, SCHED_PRESETS, AGENT_TASK_STATUSES,
});
