// <auto-generated />
using System;
using Argus.RealtimeService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Argus.RealtimeService.Migrations
{
    [DbContext(typeof(RealtimeDbContext))]
    partial class RealtimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Argus.RealtimeService.EventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceService")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex("RecordedAt");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Argus.RealtimeService.WorkerCapabilityRecord", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscribedAssetTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.ToTable("WorkerCapabilities");
                });

            modelBuilder.Entity("Argus.RealtimeService.WorkerRecord", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunningTasks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Argus.RealtimeService.WorkerScaleCommandRecord", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppliedReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousDesiredReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedDesiredReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScalerKind")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("CommandId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerType");

                    b.ToTable("WorkerScaleCommands");
                });

            modelBuilder.Entity("Argus.RealtimeService.WorkerScaleSettingRecord", b =>
                {
                    b.Property<string>("WorkerType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeploymentName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DesiredReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinReplicas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namespace")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerType");

                    b.ToTable("WorkerScaleSettings");
                });

            modelBuilder.Entity("Argus.RealtimeService.WorkerCapabilityRecord", b =>
                {
                    b.HasOne("Argus.RealtimeService.WorkerRecord", "Worker")
                        .WithOne()
                        .HasForeignKey("Argus.RealtimeService.WorkerCapabilityRecord", "WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
