( .tasks[] | select(.id == "046") ).description = "Core: Reimplement AI agent framework (tools/agent-*.sh, auto-run-agents.sh, watchdog) as a .NET Core console project named Argus.AgentCoordinator in src/Tools/. Must support: 1) configurable agent pool with MAX_CONCURRENT=5 dev, 2 devops, 2 reviewers via env vars or config file; 2) JSON-based task board at tools/.agent-tasks.json; 3) per-agent state files at tools/.agent-state-*.json; 4) heartbeat monitoring every 45s per agent; 5) crash detection via PID check (kill -0); 6) automatic task assignment from pending queue sorted by priority then ID; 7) agent prompt writing to tools/.agent-prompt-*.txt with task context; 8) invocation of opencode run --dir <workdir> to execute each agent task; 9) devops standing-task sweep every 120s for health checks; 10) reviewer cycle triggered on new git commits; 11) watchdog process that auto-restarts supervisor on crash; 12) SIGTERM/SIGINT handling for graceful shutdown and state persistence. Output: src/Tools/Argus.AgentCoordinator/Argus.AgentCoordinator.csproj + Program.cs. Use System.Text.Json for state serialization, System.Diagnostics.Process for opencode invocation."

( .tasks[] | select(.id == "047") ).description = "Enhancement #11: Custom operational metrics - Add Argus.BuildingBlocks.Observability project with shared ArgusMetrics class containing a static Meter named Argus.Recon. Define Counter<long> instruments: AssetsDiscovered (tagged assets), AssetsConfirmed (assets), RateLimitDelays (requests), TasksCompleted (tasks). Define Histogram<double> instruments: TaskDuration (ms), ScopeValidationDuration (ms). Define UpDownCounter<int>: TasksRunning (tasks). Tag ALL instruments with: program_id, worker_type, asset_type, registered_domain. Wire into Aspire dashboard and any OTLP-compatible backend (Grafana, Honeycomb, Datadog). File: src/BuildingBlocks/Argus.BuildingBlocks.Observability/ArgusMetrics.cs"

( .tasks[] | select(.id == "048") ).description = "Enhancement #12: Worker graceful draining on SIGTERM - In ArgusWorkerBackgroundService, override StopAsync to honour a configurable drain timeout. Read ARGUS_WORKER_DRAIN_TIMEOUT env var (default 60s). On StopAsync: signal no new tasks will be accepted, wait for in-flight tasks to complete up to the drain timeout. Support checkpoint writing before yielding to cancellation so a restart resumes rather than replays from scratch. Update deploy/compose.yaml to set stop_grace_period: 90s on worker services. File: src/BuildingBlocks/Argus.BuildingBlocks.Workers/ArgusWorkerBackgroundService.cs"

( .tasks[] | select(.id == "049") ).description = "Enhancement #13: FindingCandidate promotion workflow - When a worker produces a FindingCandidate asset (highest interesting score 70), AssetService emits a FindingCandidateCreated event. Build a ValidationWorker or manual operator review system: operator can promote to Finding (new asset type with severity and CVSS data fields) or dismiss with a reason. Dismissed candidates get a dismissed tag and Archived status so they do not resurface. The Finding asset type needs to be added to the AssetType enum. Files: src/Services/Argus.AssetService, src/BuildingBlocks/Argus.Contracts, new worker in src/Workers/Argus.Workers.Validation"

( .tasks[] | select(.id == "050") ).description = "Enhancement #15: Scheduled/recurring scan plans - Add CronExpression field to ScanPlanDto. Create RecurrencePolicy entity in ScanOrchestratorService database. Build a ScanSchedulerBackgroundService (BackgroundService) that checks for due recurrences every 60 seconds and auto-creates new scan plans from the template. Track LastRunAt and NextRunAt on scan plan records. Use the NCrontab or Cronos NuGet library (both lightweight, no external deps - avoid Hangfire or Quartz). File: src/Services/Argus.ScanOrchestratorService/"

( .tasks[] | select(.id == "051") ).description = "Enhancement #16: Asset graph traversal API - Add GET /assets/{assetId}/subgraph?maxDepth=3&assetTypes=Subdomain,Url endpoint to AssetService. Implement with PostgreSQL recursive CTE via Dapper or EF raw SQL: WITH RECURSIVE reachable AS (SELECT to_asset_id FROM asset_relationships WHERE from_asset_id = @rootId UNION ALL SELECT r.to_asset_id FROM asset_relationships r JOIN reachable ON r.from_asset_id = reachable.to_asset_id) SELECT * FROM assets WHERE asset_id IN (SELECT to_asset_id FROM reachable). MaxDepth parameter controls recursion depth. AssetTypes filter narrows result set. Enables UI asset graph view without pulling entire table into memory. File: src/Services/Argus.AssetService/"

( .tasks[] | select(.id == "052") ).description = "Enhancement #18: Program/scope export and import - Add GET /programs/{programId}/export endpoint returning a self-contained JSON document containing the program, all scopes, exclusions, rules, and rate limit policies. Add POST /programs/import endpoint that accepts the same format and reconstructs the full configuration. Enables: backup/restore, sharing scope templates between programmes, migrating between environments, and a scope library of pre-built templates for common bug bounty platforms. File: src/Services/Argus.ProgramScopeService/"

( .tasks[] | select(.id == "053") ).description = "Enhancement #19: Webhook notifications for high-value events - Add a WebhookService that allows configuration of webhook targets with url, event-type filters (FindingCandidateCreated, AssetConfirmed, etc.), and filters such as programId and minInterestingScore. Fire webhooks on matching events via the existing SSE subscription mechanism. Implement retry with exponential backoff. Store webhook configs in PostgreSQL so they survive restarts. Include UI for CRUD operations on webhook configs. File: src/Services/Argus.RealtimeService/"

( .tasks[] | select(.id == "054") ).description = "Enhancement #20: Scope ingestion from HackerOne/Bugcrowd APIs - Add IScopeProvider interface with ProviderName and FetchAsync(programHandle, ct) in ProgramScopeService. Implement HackerOneScopeProvider and BugcrowdScopeProvider using their public programme scope APIs. Run scheduled sync every 6 hours via a BackgroundService. On any scope change detected, publish ProgramScopeChanged event to trigger downstream cache invalidation. API keys from env vars: HACKERONE_API_TOKEN, BUGCROWD_API_TOKEN. Never hardcode secrets. File: src/Services/Argus.ProgramScopeService/Providers/"

( .tasks[] | select(.id == "055") ).description = "Enhancement #21: Bulk asset tag and enqueue endpoints with UI bindings - Wire up POST /assets/bulk/tag for BulkTagRequest and POST /assets/bulk/enqueue for BulkEnqueueRequest. These DTOs and store interface methods are already defined in AssetContracts.cs and the store interfaces. Add UI multi-select in asset grid rows with contextual tag/enqueue action buttons. Enables workflows like: select 40 subdomains, tag them all as reviewed or enqueue a fingerprint scan on all assets tagged alive. Prerequisite: deduplication (Design #22 was completed). Files: src/Services/Argus.AssetService, src/BuildingBlocks/Argus.Contracts"

( .tasks[] | select(.id == "056") ).description = "Enhancement #22: Asset staleness scoring - Add StalenessScore (int, 0-100) to AssetDto computed from (now - LastSeenAt) relative to the expected scan frequency for that asset type. Surface in the UI as a visual indicator (colour band or age column). Add minStalenessScore and maxStalenessScore to AssetQuery so operators can filter to things not checked in N days. The ScanSchedulerService uses StalenessScore as the primary scheduling signal - highest staleness gets scanned first. Files: src/Services/Argus.AssetService, src/BuildingBlocks/Argus.Contracts"
